PATCH  http://localhost:3000/api/users/edit
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUwN2UxMDMwMGNmODAwMTU4YTJlYjMiLCJpYXQiOjE2MTU5ODYxMTB9.PXJnLlPyR70l8MtqW4rlZ67OXwflS03MTbWwRS1JdBA
Content-Type: application/json

{
    "username":"admin"
}


###
POST http://localhost:3000/api/users/register

{
    "email":"nehal.fathy@gmail.com",
    "username":"nehal",
    "password":"12345",
    "gender":"female"
}